### ISSUE TITLE
How to do multispectral analysis?

### ISSUE THREAD

**Issue by percurnicus** [planetarypy/pdsspect#15]
pdsspect should be able to perform multispectral analysis, I'm just not sure on the best way to do that. I'm not as unsure about the basics of multispectral analysis as I am figuring out the best way to determine wavelengths for each image in order to perform the analysis. I have come brainstormed a couple ideas that may work:

1) Include textbox to enter the wavelength of the current image. For example, if dealing with a ML7 the user would enter ``880``nm and now pdsspect associates that image with that wavelength. PROs: Gives user flexibility and relatively not "hard" to implement. CONs: The user would have to reenter the wavelength everytime they opened pdsspect.

2) Create a model in PlanetaryPy that holds every camera's on each mission's data like filter name and wavelength. Ideally, each image's label would hold the filter wavelength as the value for the ``center_filter_wavelength``, ``wavelength``, and/or ``band_center`` parameter. Unfortunately, that is not the case for all (most?) labels. However, labels will usually (always) contain a filter name (if applicable) which enables use to find the wavelength. For example, [this label from Cassini ISS](https://pds-imaging.jpl.nasa.gov/data/cassini/cassini_orbiter/coiss_1001/data/1294561143_1295221348/N1294562651_1.LBL) has the entry ``FILTER_NAME = ("CL1","CL2") `` and then we use [this table](http://www.ciclops.org/sci/docs/ISS_Data_User_Guide_141215.pdf#page=149) to determine that the wavelength should be ``651.057``. PROs: The process would be automated for the user and would simplify the process. CONs: This would take a VERY LONG time finding all the info and translating it all into classes we could then use for other planetarPy projects. So long I'm not sure whether it is worth it. 

I'm sure there are other options I haven't thought of yet and would love to hear those options before moving foward.

**Comment by godber** [comment]
I think a combination of the two would make sense.  Some instruments would
have built in support and some would not.  People could then write their
own config files (mapping filter identifiers to wavelengths) which specify
the settings in cases where the instrument is not supported.  Then they
could submit that configuration to you to eventually be included in the
app.  Don't set the goal of supporting ALL missions ... support Pancam,
Mastcam, Mastcam-Z ... and any user submitted values.
